repos:
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.15.0
      hooks:
        - id: yamllint
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        - id: flake8
          args: [--max-line-length=120, ignore = F401,E711]  #  Why is this not using setup.cfg?
        - id: end-of-file-fixer
        - id: check-docstring-first
        - id: check-json
        - id: check-yaml
        - id: debug-statements
        - id: requirements-txt-fixer
        - id: check-added-large-files
        - id: check-merge-conflict
    -   repo: https://github.com/pre-commit/mirrors-pylint
        rev: 'v2.3.1'
        hooks:
        -   id: pylint
            exclude: '^(tests/|integration_tests/|utils/|docs/conf.py)'
