# Use this file to test a pre-built datacube-core docker image, tagged with opendatacube:local
# with the following command:
#
#  docker-compose -f docker-compose-test.yml run --rm odc
#

version: '3'

services:
  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_USER=odcintegration
      - POSTGRES_PASSWORD=opendatacubepassword

  odc:
    image: opendatacube/datacube-core:${ODC_DOCKER_TAG}
    depends_on:
      - postgres
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=odcintegration
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=odcintegration
    working_dir: /tmp/code
    #    command: pytest -m "not netcdf and not s3aio" -r a --cov datacube --durations=5 tests integration_tests --odc-config-file odcintegration-docker.conf
    command: docker/run-tests-conda.sh
    volumes:
        - ../:/tmp/code
